// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaHorarios.Datos.Contexto;

#nullable disable

namespace SistemaHorarios.Datos.Migrations
{
    [DbContext(typeof(SistemaHorariosDbContext))]
    [Migration("20260517154024_AgregarCantidadGruposMateria")]
    partial class AgregarCantidadGruposMateria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SistemaHorarios.Modelos.Entidades.DisponibilidadDocente", b =>
                {
                    b.Property<int>("IdDisponibilidadDocente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDisponibilidadDocente"));

                    b.Property<string>("Dia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Disponible")
                        .HasColumnType("tinyint(1)");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time(6)");

                    b.Property<int>("IdDocente")
                        .HasColumnType("int");

                    b.HasKey("IdDisponibilidadDocente");

                    b.ToTable("DisponibilidadesDocentes");
                });

            modelBuilder.Entity("SistemaHorarios.Modelos.Entidades.Docente", b =>
                {
                    b.Property<int>("IdDocente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDocente"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CorreoInstitucional")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdDocente");

                    b.ToTable("Docentes");
                });

            modelBuilder.Entity("SistemaHorarios.Modelos.Entidades.FranjaHoraria", b =>
                {
                    b.Property<int>("IdFranjaHoraria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdFranjaHoraria"));

                    b.Property<bool>("Activa")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time(6)");

                    b.HasKey("IdFranjaHoraria");

                    b.ToTable("FranjasHorarias");
                });

            modelBuilder.Entity("SistemaHorarios.Modelos.Entidades.Grupo", b =>
                {
                    b.Property<int>("IdGrupo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdGrupo"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CantidadEstudiantes")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdPlanAcademico")
                        .HasColumnType("int");

                    b.Property<string>("Jornada")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NumeroSemestre")
                        .HasColumnType("int");

                    b.Property<string>("TipoGrupo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdGrupo");

                    b.HasIndex("IdPlanAcademico");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("SistemaHorarios.Modelos.Entidades.Materia", b =>
                {
                    b.Property<int>("IdMateria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdMateria"));

                    b.Property<bool>("Activa")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CantidadGrupos")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Creditos")
                        .HasColumnType("int");

                    b.Property<int>("IntensidadHorariaSemanal")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Semestre")
                        .HasColumnType("int");

                    b.HasKey("IdMateria");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("SistemaHorarios.Modelos.Entidades.MateriaPlan", b =>
                {
                    b.Property<int>("IdMateriaPlan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdMateriaPlan"));

                    b.Property<int>("IdMateria")
                        .HasColumnType("int");

                    b.Property<int>("IdSemestrePlan")
                        .HasColumnType("int");

                    b.HasKey("IdMateriaPlan");

                    b.HasIndex("IdMateria");

                    b.HasIndex("IdSemestrePlan", "IdMateria")
                        .IsUnique();

                    b.ToTable("MateriasPlan");
                });

            modelBuilder.Entity("SistemaHorarios.Modelos.Entidades.PlanAcademico", b =>
                {
                    b.Property<int>("IdPlanAcademico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPlanAcademico"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Programa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdPlanAcademico");

                    b.ToTable("PlanesAcademicos");
                });

            modelBuilder.Entity("SistemaHorarios.Modelos.Entidades.Prerrequisito", b =>
                {
                    b.Property<int>("IdPrerrequisito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPrerrequisito"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IdMateria")
                        .HasColumnType("int");

                    b.Property<int>("IdMateriaPrerrequisito")
                        .HasColumnType("int");

                    b.HasKey("IdPrerrequisito");

                    b.ToTable("Prerrequisitos");
                });

            modelBuilder.Entity("SistemaHorarios.Modelos.Entidades.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            IdRol = 1,
                            Activo = true,
                            Descripcion = "",
                            Nombre = "Administrador"
                        },
                        new
                        {
                            IdRol = 2,
                            Activo = true,
                            Descripcion = "",
                            Nombre = "Coordinador"
                        },
                        new
                        {
                            IdRol = 3,
                            Activo = true,
                            Descripcion = "",
                            Nombre = "Docente"
                        });
                });

            modelBuilder.Entity("SistemaHorarios.Modelos.Entidades.SemestrePlan", b =>
                {
                    b.Property<int>("IdSemestrePlan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdSemestrePlan"));

                    b.Property<int>("IdPlanAcademico")
                        .HasColumnType("int");

                    b.Property<int>("NumeroSemestre")
                        .HasColumnType("int");

                    b.HasKey("IdSemestrePlan");

                    b.HasIndex("IdPlanAcademico", "NumeroSemestre")
                        .IsUnique();

                    b.ToTable("SemestresPlan");
                });

            modelBuilder.Entity("SistemaHorarios.Modelos.Entidades.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CorreoInstitucional")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdRol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemaHorarios.Modelos.Entidades.Grupo", b =>
                {
                    b.HasOne("SistemaHorarios.Modelos.Entidades.PlanAcademico", "PlanAcademico")
                        .WithMany()
                        .HasForeignKey("IdPlanAcademico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanAcademico");
                });

            modelBuilder.Entity("SistemaHorarios.Modelos.Entidades.MateriaPlan", b =>
                {
                    b.HasOne("SistemaHorarios.Modelos.Entidades.Materia", "Materia")
                        .WithMany()
                        .HasForeignKey("IdMateria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaHorarios.Modelos.Entidades.SemestrePlan", "SemestrePlan")
                        .WithMany("MateriasPlan")
                        .HasForeignKey("IdSemestrePlan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Materia");

                    b.Navigation("SemestrePlan");
                });

            modelBuilder.Entity("SistemaHorarios.Modelos.Entidades.SemestrePlan", b =>
                {
                    b.HasOne("SistemaHorarios.Modelos.Entidades.PlanAcademico", "PlanAcademico")
                        .WithMany("Semestres")
                        .HasForeignKey("IdPlanAcademico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanAcademico");
                });

            modelBuilder.Entity("SistemaHorarios.Modelos.Entidades.Usuario", b =>
                {
                    b.HasOne("SistemaHorarios.Modelos.Entidades.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SistemaHorarios.Modelos.Entidades.PlanAcademico", b =>
                {
                    b.Navigation("Semestres");
                });

            modelBuilder.Entity("SistemaHorarios.Modelos.Entidades.SemestrePlan", b =>
                {
                    b.Navigation("MateriasPlan");
                });
#pragma warning restore 612, 618
        }
    }
}
