// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaHorarios.Datos.Contexto;

#nullable disable

namespace SistemaHorarios.Datos.Migrations
{
    [DbContext(typeof(SistemaHorariosDbContext))]
    partial class SistemaHorariosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("SistemaHorarios.Modelos.Entidades.DisponibilidadDocente", b =>
                {
                    b.Property<int>("IdDisponibilidadDocente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disponible")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdDocente")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdDisponibilidadDocente");

                    b.ToTable("DisponibilidadesDocentes");
                });

            modelBuilder.Entity("SistemaHorarios.Modelos.Entidades.Docente", b =>
                {
                    b.Property<int>("IdDocente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorreoInstitucional")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdDocente");

                    b.ToTable("Docentes");
                });

            modelBuilder.Entity("SistemaHorarios.Modelos.Entidades.DocenteMateria", b =>
                {
                    b.Property<int>("IdDocenteMateria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdDocente")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdMateria")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdDocenteMateria");

                    b.HasIndex("IdDocente");

                    b.HasIndex("IdMateria");

                    b.ToTable("DocenteMaterias");
                });

            modelBuilder.Entity("SistemaHorarios.Modelos.Entidades.FranjaHoraria", b =>
                {
                    b.Property<int>("IdFranjaHoraria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("TEXT");

                    b.HasKey("IdFranjaHoraria");

                    b.ToTable("FranjasHorarias");
                });

            modelBuilder.Entity("SistemaHorarios.Modelos.Entidades.Grupo", b =>
                {
                    b.Property<int>("IdGrupo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadEstudiantes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Dias")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdPlanAcademico")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Jornada")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Materia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroSemestre")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoGrupo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdGrupo");

                    b.HasIndex("IdPlanAcademico");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("SistemaHorarios.Modelos.Entidades.Horario", b =>
                {
                    b.Property<int>("IdHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdDocente")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdFranjaHoraria")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdGrupo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdMateria")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdHorario");

                    b.HasIndex("IdDocente");

                    b.HasIndex("IdFranjaHoraria");

                    b.HasIndex("IdGrupo");

                    b.HasIndex("IdMateria");

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("SistemaHorarios.Modelos.Entidades.Materia", b =>
                {
                    b.Property<int>("IdMateria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadGrupos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Creditos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntensidadHorariaSemanal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Semestre")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdMateria");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("SistemaHorarios.Modelos.Entidades.MateriaPlan", b =>
                {
                    b.Property<int>("IdMateriaPlan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdMateria")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdSemestrePlan")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdMateriaPlan");

                    b.HasIndex("IdMateria");

                    b.HasIndex("IdSemestrePlan", "IdMateria")
                        .IsUnique();

                    b.ToTable("MateriasPlan");
                });

            modelBuilder.Entity("SistemaHorarios.Modelos.Entidades.PlanAcademico", b =>
                {
                    b.Property<int>("IdPlanAcademico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Programa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdPlanAcademico");

                    b.ToTable("PlanesAcademicos");
                });

            modelBuilder.Entity("SistemaHorarios.Modelos.Entidades.Prerrequisito", b =>
                {
                    b.Property<int>("IdPrerrequisito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdMateria")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdMateriaPrerrequisito")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdPrerrequisito");

                    b.ToTable("Prerrequisitos");
                });

            modelBuilder.Entity("SistemaHorarios.Modelos.Entidades.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            IdRol = 1,
                            Activo = true,
                            Descripcion = "",
                            Nombre = "Administrador"
                        },
                        new
                        {
                            IdRol = 2,
                            Activo = true,
                            Descripcion = "",
                            Nombre = "Coordinador"
                        },
                        new
                        {
                            IdRol = 3,
                            Activo = true,
                            Descripcion = "",
                            Nombre = "Docente"
                        });
                });

            modelBuilder.Entity("SistemaHorarios.Modelos.Entidades.SemestrePlan", b =>
                {
                    b.Property<int>("IdSemestrePlan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdPlanAcademico")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumeroSemestre")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdSemestrePlan");

                    b.HasIndex("IdPlanAcademico", "NumeroSemestre")
                        .IsUnique();

                    b.ToTable("SemestresPlan");
                });

            modelBuilder.Entity("SistemaHorarios.Modelos.Entidades.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorreoInstitucional")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdRol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdRol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemaHorarios.Modelos.Entidades.DocenteMateria", b =>
                {
                    b.HasOne("SistemaHorarios.Modelos.Entidades.Docente", "Docente")
                        .WithMany()
                        .HasForeignKey("IdDocente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaHorarios.Modelos.Entidades.Materia", "Materia")
                        .WithMany()
                        .HasForeignKey("IdMateria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Docente");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("SistemaHorarios.Modelos.Entidades.Grupo", b =>
                {
                    b.HasOne("SistemaHorarios.Modelos.Entidades.PlanAcademico", "PlanAcademico")
                        .WithMany()
                        .HasForeignKey("IdPlanAcademico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanAcademico");
                });

            modelBuilder.Entity("SistemaHorarios.Modelos.Entidades.Horario", b =>
                {
                    b.HasOne("SistemaHorarios.Modelos.Entidades.Docente", "Docente")
                        .WithMany()
                        .HasForeignKey("IdDocente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaHorarios.Modelos.Entidades.FranjaHoraria", "FranjaHoraria")
                        .WithMany()
                        .HasForeignKey("IdFranjaHoraria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaHorarios.Modelos.Entidades.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("IdGrupo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaHorarios.Modelos.Entidades.Materia", "Materia")
                        .WithMany()
                        .HasForeignKey("IdMateria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Docente");

                    b.Navigation("FranjaHoraria");

                    b.Navigation("Grupo");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("SistemaHorarios.Modelos.Entidades.MateriaPlan", b =>
                {
                    b.HasOne("SistemaHorarios.Modelos.Entidades.Materia", "Materia")
                        .WithMany()
                        .HasForeignKey("IdMateria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaHorarios.Modelos.Entidades.SemestrePlan", "SemestrePlan")
                        .WithMany("MateriasPlan")
                        .HasForeignKey("IdSemestrePlan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Materia");

                    b.Navigation("SemestrePlan");
                });

            modelBuilder.Entity("SistemaHorarios.Modelos.Entidades.SemestrePlan", b =>
                {
                    b.HasOne("SistemaHorarios.Modelos.Entidades.PlanAcademico", "PlanAcademico")
                        .WithMany("Semestres")
                        .HasForeignKey("IdPlanAcademico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanAcademico");
                });

            modelBuilder.Entity("SistemaHorarios.Modelos.Entidades.Usuario", b =>
                {
                    b.HasOne("SistemaHorarios.Modelos.Entidades.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SistemaHorarios.Modelos.Entidades.PlanAcademico", b =>
                {
                    b.Navigation("Semestres");
                });

            modelBuilder.Entity("SistemaHorarios.Modelos.Entidades.SemestrePlan", b =>
                {
                    b.Navigation("MateriasPlan");
                });
#pragma warning restore 612, 618
        }
    }
}
